#!/usr/bin/env perl

use v5.36.0;
use warnings;

open my $fh, ">", "unzip_gen.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate-unzip.pl; DO NOT EDIT.

package it

import (
    "iter"

    "github.com/shogo82148/hi/tuple"
)
END

for my $n(2..16) {
    say $fh "";
    my $types = join ", ", map { "T$_" } 1..$n;
    my $returns = join ", ", map { "func(func(T$_)bool)" } 1..$n;
    say $fh "// Unzip$n converts an iterator of $n-tuple to iterators of each elements.";
    say $fh "func Unzip${n}[$types any](seq iter.Seq[tuple.Tuple${n}[$types]]) ($returns) {";
    say $fh "s := Tee(seq, ${n})";
    print $fh 'return ';
    for my $i(1..$n) {
        say $fh "func (yield func(T$i) bool) {";
        say $fh "for v := range s[@{[$i-1]}] {";
        say $fh "if !yield(v.V${i}) { return }";
        say $fh "}";
        if ($i == $n) {
            say $fh "}";
        } else {
            say $fh "}, ";
        }
    }
    say $fh "}";
}

system("gofmt -s -w unzip_gen.go");

close($fh);
