#!/usr/bin/env perl

use v5.36.0;
use warnings;

open my $fh, ">", "unzip_gen.go" or die "failed to open: $!";

print $fh <<'END';
// Code generated by generate_zip.pl; DO NOT EDIT.

package list

import (
    "github.com/shogo82148/hi/tuple"
)
END

sub mapJoin :prototype(&$) ($f, $n) {
    return join ", ", map { $f->($_) } 1..$n;
}

for my $n(2..16) {
    say $fh "";
    my $types = mapJoin { "T$_" } $n;

    say $fh "// Unip$n converts a list of $n-tuple to lists of each elements.";
    say $fh "func Unzip${n}[$types any](l *List[tuple.Tuple${n}[$types]]) (" . (mapJoin { "*List[T$_]" } $n) . ") {";
    for my $i (1..$n) {
        say $fh "	l$i := new(List[T$i]).Init()";
    }
    say $fh "	for e := l.Front(); e != nil; e = e.Next() {";
    for my $i (1..$n) {
        say $fh "		l$i.PushBack(e.Value.V$i)";
    }
    say $fh "	}";
    say $fh "	return " . mapJoin { "l$_" } $n;
    say $fh "}";
}

system("gofmt -s -w unzip_gen.go");

close($fh);
