name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
          cache: true

      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: profile.cov
          flags: Go-${{ matrix.go }}

  # test for range over func https://github.com/golang/go/issues/61405
  iter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          gotip version

      - name: test
        env:
          GOEXPERIMENT: rangefunc
        run: |
          go mod edit -go=1.22
          gotip test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: profile.cov
          flags: Go-tip
